## All NBA 2020 PREDICTION

### In this project, I'm going to use NBA per game data(2014-2020) from basketball reference to predict 2020 ALL NBA players.Here ALL NBA players refer to combination of ALL NBA first team+second team+thrid team. I gathered data from 2014-2019 ALL NBA teams and use per game statistics from 2014 to 2020 to predict ALL NBA 2020 teams

In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

### 1.Importing per game data from basketballreference.com

In [17]:
###selecting years between 2014 and 2020
years = np.arange(2014,2021,1)
years

array([2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [18]:
base_url = 'https://www.basketball-reference.com/leagues/NBA_{}_per_game.html'

In [19]:
seasons_per_game = pd.DataFrame()

In [20]:
for year in years:
    req_url = base_url.format(year)
    req = requests.get(req_url)
    soup = BeautifulSoup(req.content, 'html.parser')
    table = soup.find('table', {'id':'per_game_stats'})
    df = pd.read_html(str(table))[0]
    df['Year'] = year
    
    seasons_per_game = seasons_per_game.append(df)

In [21]:
##Take a look at our initial data
seasons_per_game

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Quincy Acy,SF,23,TOT,63,0,13.4,1.0,2.2,...,1.1,2.3,3.4,0.4,0.4,0.4,0.5,1.9,2.7,2014
1,1,Quincy Acy,SF,23,TOR,7,0,8.7,0.9,2.0,...,0.7,1.4,2.1,0.6,0.6,0.4,0.3,1.1,2.7,2014
2,1,Quincy Acy,SF,23,SAC,56,0,14.0,1.1,2.3,...,1.2,2.4,3.6,0.4,0.3,0.4,0.5,2.0,2.7,2014
3,2,Steven Adams,C,20,OKC,81,20,14.8,1.1,2.3,...,1.8,2.3,4.1,0.5,0.5,0.7,0.9,2.5,3.3,2014
4,3,Jeff Adrien,PF,27,TOT,53,12,18.1,2.7,5.2,...,1.9,3.8,5.8,0.7,0.5,0.7,0.7,2.0,6.8,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,493,Thaddeus Young,PF,31,CHI,50,6,23.3,3.8,8.8,...,1.4,3.2,4.6,1.8,1.1,0.3,1.4,1.9,9.4,2020
545,494,Trae Young,PG,21,ATL,45,45,34.9,9.1,20.6,...,0.6,4.0,4.6,9.0,1.1,0.1,4.8,1.6,29.0,2020
546,495,Cody Zeller,C,27,CHO,46,27,23.3,4.4,8.5,...,2.8,4.3,7.1,1.5,0.7,0.5,1.3,2.5,11.2,2020
547,496,Ante Žižić,C,23,CLE,16,0,9.9,1.8,3.1,...,0.9,2.6,3.4,0.2,0.4,0.3,0.3,1.3,4.3,2020
548,497,Ivica Zubac,C,22,LAC,49,47,17.7,3.2,5.5,...,2.7,4.4,7.1,1.0,0.2,1.0,0.9,2.3,8.0,2020

### 2.Data manipulation and cleaning

In [22]:
###removing team,player name,pos and rank column
nbadata=seasons_per_game.iloc[:,3:31]
nbadata1=nbadata.reset_index()
nbadata2=nbadata1.iloc[:,0:28]
nbadata3=nbadata2.iloc[:,1:28]
nbadata4=nbadata3.drop(['Tm'],axis=1)
nbadata4=nbadata4.fillna(0.0)

,Age,Tm,G,GS,MP,FG,FGA,FG%,3P,3PA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,23,TOT,63,0,13.4,1.0,2.2,.468,0.1,0.2,...,1.1,2.3,3.4,0.4,0.4,0.4,0.5,1.9,2.7,2014
1,23,TOR,7,0,8.7,0.9,2.0,.429,0.3,0.7,...,0.7,1.4,2.1,0.6,0.6,0.4,0.3,1.1,2.7,2014
2,23,SAC,56,0,14.0,1.1,2.3,.472,0.0,0.2,...,1.2,2.4,3.6,0.4,0.3,0.4,0.5,2.0,2.7,2014
3,20,OKC,81,20,14.8,1.1,2.3,.503,0.0,0.0,...,1.8,2.3,4.1,0.5,0.5,0.7,0.9,2.5,3.3,2014
4,27,TOT,53,12,18.1,2.7,5.2,.520,0.0,0.0,...,1.9,3.8,5.8,0.7,0.5,0.7,0.7,2.0,6.8,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,31,CHI,50,6,23.3,3.8,8.8,.434,1.1,3.2,...,1.4,3.2,4.6,1.8,1.1,0.3,1.4,1.9,9.4,2020
545,21,ATL,45,45,34.9,9.1,20.6,.444,3.4,9.2,...,0.6,4.0,4.6,9.0,1.1,0.1,4.8,1.6,29.0,2020
546,27,CHO,46,27,23.3,4.4,8.5,.522,0.4,1.5,...,2.8,4.3,7.1,1.5,0.7,0.5,1.3,2.5,11.2,2020
547,23,CLE,16,0,9.9,1.8,3.1,.571,0.0,0.0,...,0.9,2.6,3.4,0.2,0.4,0.3,0.3,1.3,4.3,2020
548,22,LAC,49,47,17.7,3.2,5.5,.578,0.0,0.0,...,2.7,4.4,7.1,1.0,0.2,1.0,0.9,2.3,8.0,2020

In [25]:
# A look of new data after some manipulations
nbadata4

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,23,63,0,13.4,1.0,2.2,.468,0.1,0.2,.267,...,.660,1.1,2.3,3.4,0.4,0.4,0.4,0.5,1.9,2.7
1,23,7,0,8.7,0.9,2.0,.429,0.3,0.7,.400,...,.625,0.7,1.4,2.1,0.6,0.6,0.4,0.3,1.1,2.7
2,23,56,0,14.0,1.1,2.3,.472,0.0,0.2,.200,...,.667,1.2,2.4,3.6,0.4,0.3,0.4,0.5,2.0,2.7
3,20,81,20,14.8,1.1,2.3,.503,0.0,0.0,0,...,.581,1.8,2.3,4.1,0.5,0.5,0.7,0.9,2.5,3.3
4,27,53,12,18.1,2.7,5.2,.520,0.0,0.0,0,...,.639,1.9,3.8,5.8,0.7,0.5,0.7,0.7,2.0,6.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4498,31,50,6,23.3,3.8,8.8,.434,1.1,3.2,.333,...,.596,1.4,3.2,4.6,1.8,1.1,0.3,1.4,1.9,9.4
4499,21,45,45,34.9,9.1,20.6,.444,3.4,9.2,.367,...,.841,0.6,4.0,4.6,9.0,1.1,0.1,4.8,1.6,29.0
4500,27,46,27,23.3,4.4,8.5,.522,0.4,1.5,.254,...,.686,2.8,4.3,7.1,1.5,0.7,0.5,1.3,2.5,11.2
4501,23,16,0,9.9,1.8,3.1,.571,0.0,0.0,0,...,.867,0.9,2.6,3.4,0.2,0.4,0.3,0.3,1.3,4.3
4502,22,49,47,17.7,3.2,5.5,.578,0.0,0.0,.000,...,.741,2.7,4.4,7.1,1.0,0.2,1.0,0.9,2.3,8.0

In [28]:
###Creating a new dataframe to mark ALL NBA players from 2014-2019
newd=seasons_per_game[['Player','Year']]
newd.to_csv('label.csv', sep='\t')

             Player  Year
0        Quincy Acy  2014
1        Quincy Acy  2014
2        Quincy Acy  2014
3      Steven Adams  2014
4       Jeff Adrien  2014
..              ...   ...
544  Thaddeus Young  2020
545      Trae Young  2020
546     Cody Zeller  2020
547      Ante Žižić  2020
548     Ivica Zubac  2020

[4503 rows x 2 columns]

### Create a new dataframe containing information about past ALL NBA players from 2014-2019

In [75]:
allnba=pd.read_csv('label.csv')
allnba

              Player  Year  ALLNBA
0         Quincy Acy  2014       0
1         Quincy Acy  2014       0
2         Quincy Acy  2014       0
3       Steven Adams  2014       0
4        Jeff Adrien  2014       0
...              ...   ...     ...
4498  Thaddeus Young  2020       0
4499      Trae Young  2020       0
4500     Cody Zeller  2020       0
4501      Ante Žižić  2020       0
4502     Ivica Zubac  2020       0

[4503 rows x 3 columns]

### Split per game data into training data and testing data

In [33]:
nbadata_train=nbadata4.loc[allnba.Year < 2020]
nbadata_test=nbadata4.loc[allnba.Year==2020]

In [36]:
nbadata_test

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
3954,26,44,44,26.7,4.5,7.5,.600,0.0,0.0,.000,...,.579,3.4,5.9,9.3,2.6,0.7,1.1,1.5,1.9,10.8
3955,22,48,48,34.6,6.0,10.4,.581,0.0,0.2,.091,...,.689,2.5,7.9,10.5,4.7,1.2,1.2,2.8,2.5,15.7
3956,34,44,44,33.0,7.4,14.5,.508,1.2,2.7,.425,...,.840,2.0,5.5,7.5,2.3,0.6,1.7,1.4,2.4,18.9
3957,21,39,0,12.7,2.0,5.8,.342,1.0,3.0,.342,...,.607,0.2,1.8,2.0,1.9,0.3,0.2,1.0,1.1,5.4
3958,24,30,0,16.6,2.6,5.9,.449,1.1,3.0,.363,...,.857,0.2,2.0,2.2,1.4,0.2,0.0,0.8,1.2,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4498,31,50,6,23.3,3.8,8.8,.434,1.1,3.2,.333,...,.596,1.4,3.2,4.6,1.8,1.1,0.3,1.4,1.9,9.4
4499,21,45,45,34.9,9.1,20.6,.444,3.4,9.2,.367,...,.841,0.6,4.0,4.6,9.0,1.1,0.1,4.8,1.6,29.0
4500,27,46,27,23.3,4.4,8.5,.522,0.4,1.5,.254,...,.686,2.8,4.3,7.1,1.5,0.7,0.5,1.3,2.5,11.2
4501,23,16,0,9.9,1.8,3.1,.571,0.0,0.0,0,...,.867,0.9,2.6,3.4,0.2,0.4,0.3,0.3,1.3,4.3
4502,22,49,47,17.7,3.2,5.5,.578,0.0,0.0,.000,...,.741,2.7,4.4,7.1,1.0,0.2,1.0,0.9,2.3,8.0

In [38]:
nbadata_test1=nbadata_test.reset_index()
nbadata_test1

,index,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,3954,26,44,44,26.7,4.5,7.5,.600,0.0,0.0,...,.579,3.4,5.9,9.3,2.6,0.7,1.1,1.5,1.9,10.8
1,3955,22,48,48,34.6,6.0,10.4,.581,0.0,0.2,...,.689,2.5,7.9,10.5,4.7,1.2,1.2,2.8,2.5,15.7
2,3956,34,44,44,33.0,7.4,14.5,.508,1.2,2.7,...,.840,2.0,5.5,7.5,2.3,0.6,1.7,1.4,2.4,18.9
3,3957,21,39,0,12.7,2.0,5.8,.342,1.0,3.0,...,.607,0.2,1.8,2.0,1.9,0.3,0.2,1.0,1.1,5.4
4,3958,24,30,0,16.6,2.6,5.9,.449,1.1,3.0,...,.857,0.2,2.0,2.2,1.4,0.2,0.0,0.8,1.2,7.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,4498,31,50,6,23.3,3.8,8.8,.434,1.1,3.2,...,.596,1.4,3.2,4.6,1.8,1.1,0.3,1.4,1.9,9.4
545,4499,21,45,45,34.9,9.1,20.6,.444,3.4,9.2,...,.841,0.6,4.0,4.6,9.0,1.1,0.1,4.8,1.6,29.0
546,4500,27,46,27,23.3,4.4,8.5,.522,0.4,1.5,...,.686,2.8,4.3,7.1,1.5,0.7,0.5,1.3,2.5,11.2
547,4501,23,16,0,9.9,1.8,3.1,.571,0.0,0.0,...,.867,0.9,2.6,3.4,0.2,0.4,0.3,0.3,1.3,4.3
548,4502,22,49,47,17.7,3.2,5.5,.578,0.0,0.0,...,.741,2.7,4.4,7.1,1.0,0.2,1.0,0.9,2.3,8.0

In [39]:
nba_test=nbadata_test1.drop(['index'],axis=1)

In [41]:
nba_test['Age']=pd.to_numeric(nba_test['Age'],errors='coerce')
nba_test['G']=pd.to_numeric(nba_test['G'],errors='coerce')
nba_test['GS']=pd.to_numeric(nba_test['GS'],errors='coerce')
nba_test['MP']=pd.to_numeric(nba_test['MP'],errors='coerce')
nba_test['FG']=pd.to_numeric(nba_test['FG'],errors='coerce')
nba_test['FGA']=pd.to_numeric(nba_test['FGA'],errors='coerce')
nba_test['FG%']=pd.to_numeric(nba_test['FG%'],errors='coerce')
nba_test['3P']=pd.to_numeric(nba_test['3P'],errors='coerce')
nba_test['3PA']=pd.to_numeric(nba_test['3PA'],errors='coerce')
nba_test['3P%']=pd.to_numeric(nba_test['3P%'],errors='coerce')
nba_test['2P']=pd.to_numeric(nba_test['2P'],errors='coerce')
nba_test['2PA']=pd.to_numeric(nba_test['2PA'],errors='coerce')
nba_test['2P%']=pd.to_numeric(nba_test['2P%'],errors='coerce')
nba_test['eFG%']=pd.to_numeric(nba_test['eFG%'],errors='coerce')
nba_test['FT']=pd.to_numeric(nba_test['FT'],errors='coerce')
nba_test['FTA']=pd.to_numeric(nba_test['FTA'],errors='coerce')
nba_test['FT%']=pd.to_numeric(nba_test['FT%'],errors='coerce')
nba_test['ORB']=pd.to_numeric(nba_test['ORB'],errors='coerce')
nba_test['DRB']=pd.to_numeric(nba_test['DRB'],errors='coerce')
nba_test['TRB']=pd.to_numeric(nba_test['TRB'],errors='coerce')
nba_test['AST']=pd.to_numeric(nba_test['AST'],errors='coerce')
nba_test['STL']=pd.to_numeric(nba_test['STL'],errors='coerce')
nba_test['BLK']=pd.to_numeric(nba_test['BLK'],errors='coerce')
nba_test['TOV']=pd.to_numeric(nba_test['TOV'],errors='coerce')
nba_test['PF']=pd.to_numeric(nba_test['PF'],errors='coerce')
nba_test['PTS']=pd.to_numeric(nba_test['PTS'],errors='coerce')

In [42]:
###Normalizing data
nbatest_norm = (nba_test - nba_test.mean()) / (nba_test.std() +np.spacing(0))
nbatest_norm

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,0.109375,0.841402,1.681823,0.775395,0.591630,0.119424,1.269962,-1.048754,-1.169549,-1.835837,...,-0.360165,3.343674,1.633579,2.236253,0.413448,0.232112,1.652252,0.468668,0.225285,0.356145
1,-0.876407,1.091394,1.907644,1.585234,1.231966,0.709761,1.127737,-1.048754,-1.080934,-1.238308,...,0.065906,2.178136,2.671556,2.704601,1.584638,1.394889,1.887968,2.005746,0.901786,1.104965
2,2.080939,0.841402,1.681823,1.421216,1.829613,1.544376,0.581292,0.331185,0.026753,0.954821,...,0.650786,1.530616,1.425983,1.533730,0.246136,-0.000443,3.066544,0.350431,0.789036,1.593991
3,-1.122852,0.528912,-0.802200,-0.659763,-0.475597,-0.226635,-0.661309,0.101196,0.159676,0.409822,...,-0.251710,-0.800459,-0.494275,-0.612867,0.023052,-0.698109,-0.469186,-0.122516,-0.676715,-0.469086
4,-0.383516,-0.033570,-0.802200,-0.259969,-0.219463,-0.206279,0.139645,0.216190,0.159676,0.547713,...,0.716633,-0.800459,-0.390477,-0.534809,-0.255803,-0.930664,-0.940616,-0.358989,-0.563965,-0.163445
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,1.341602,1.216390,-0.463469,0.426857,0.292806,0.384058,0.027361,0.216190,0.248291,0.350726,...,-0.294317,0.753591,0.232309,0.401888,-0.032719,1.162333,-0.233470,0.350431,0.225285,0.142196
545,-1.122852,0.903900,1.738278,1.615988,2.555328,2.786119,0.102217,2.861073,2.906739,0.573978,...,0.654659,-0.282442,0.647500,0.401888,3.982787,1.162333,-0.704901,4.370480,-0.112965,3.137479
546,0.355820,0.966398,0.722087,0.426857,0.548941,0.322989,0.686090,-0.588774,-0.504936,-0.168009,...,0.054286,2.566649,0.803197,1.377614,-0.200032,0.232112,0.237960,0.232194,0.901786,0.417273
547,-0.629962,-0.908543,-0.802200,-0.946794,-0.560975,-0.776259,1.052881,-1.048754,-1.169549,-1.835837,...,0.755367,0.106070,-0.079084,-0.066461,-0.925054,-0.465554,-0.233470,-0.950173,-0.451215,-0.637189
548,-0.876407,1.153892,1.851188,-0.147206,0.036672,-0.287704,1.105280,-1.048754,-1.169549,-1.835837,...,0.267322,2.437145,0.855096,1.377614,-0.478886,-0.930664,1.416537,-0.240753,0.676286,-0.071753

In [43]:
nbatest_norm=nbatest_norm.fillna(0)

In [44]:
nba_train=nbadata_train

In [45]:
nba_train['Age']=pd.to_numeric(nba_train['Age'],errors='coerce')
nba_train['G']=pd.to_numeric(nba_train['G'],errors='coerce')
nba_train['GS']=pd.to_numeric(nba_train['GS'],errors='coerce')
nba_train['MP']=pd.to_numeric(nba_train['MP'],errors='coerce')
nba_train['FG']=pd.to_numeric(nba_train['FG'],errors='coerce')
nba_train['FGA']=pd.to_numeric(nba_train['FGA'],errors='coerce')
nba_train['FG%']=pd.to_numeric(nba_train['FG%'],errors='coerce')
nba_train['3P']=pd.to_numeric(nba_train['3P'],errors='coerce')
nba_train['3PA']=pd.to_numeric(nba_train['3PA'],errors='coerce')
nba_train['3P%']=pd.to_numeric(nba_train['3P%'],errors='coerce')
nba_train['2P']=pd.to_numeric(nba_train['2P'],errors='coerce')
nba_train['2PA']=pd.to_numeric(nba_train['2PA'],errors='coerce')
nba_train['2P%']=pd.to_numeric(nba_train['2P%'],errors='coerce')
nba_train['eFG%']=pd.to_numeric(nba_train['eFG%'],errors='coerce')
nba_train['FT']=pd.to_numeric(nba_train['FT'],errors='coerce')
nba_train['FTA']=pd.to_numeric(nba_train['FTA'],errors='coerce')
nba_train['FT%']=pd.to_numeric(nba_train['FT%'],errors='coerce')
nba_train['ORB']=pd.to_numeric(nba_train['ORB'],errors='coerce')
nba_train['DRB']=pd.to_numeric(nba_train['DRB'],errors='coerce')
nba_train['TRB']=pd.to_numeric(nba_train['TRB'],errors='coerce')
nba_train['AST']=pd.to_numeric(nba_train['AST'],errors='coerce')
nba_train['STL']=pd.to_numeric(nba_train['STL'],errors='coerce')
nba_train['BLK']=pd.to_numeric(nba_train['BLK'],errors='coerce')
nba_train['TOV']=pd.to_numeric(nba_train['TOV'],errors='coerce')
nba_train['PF']=pd.to_numeric(nba_train['PF'],errors='coerce')
nba_train['PTS']=pd.to_numeric(nba_train['PTS'],errors='coerce')

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/Users/jerrytong/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [46]:
nbatrain_norm = (nba_train - nba_train.mean()) / (nba_train.std() +np.spacing(0))

In [47]:
nbatrain_norm=nbatrain_norm.fillna(0)
nbatrain_norm

,Age,G,GS,MP,FG,FGA,FG%,3P,3PA,3P%,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,-0.817849,0.643331,-0.781435,-0.631652,-0.953736,-1.018185,0.305599,-0.855753,-0.991811,-0.016826,...,-0.151126,0.365088,-0.160172,0.000088,-0.801776,-0.497660,0.076019,-0.754399,0.294617,-0.927726
1,-0.817849,-1.466554,-0.781435,-1.141187,-1.002287,-1.063962,-0.042997,-0.581419,-0.728361,0.783200,...,-0.309232,-0.155763,-0.669215,-0.542360,-0.684699,-0.029628,0.076019,-1.012499,-0.740194,-0.927726
2,-0.817849,0.379596,-0.781435,-0.566605,-0.905184,-0.995297,0.341353,-0.992920,-0.991811,-0.419847,...,-0.119505,0.495300,-0.103612,0.083541,-0.801776,-0.731676,0.076019,-0.754399,0.423968,-0.927726
3,-1.537024,1.321509,-0.039503,-0.479876,-0.905184,-0.995297,0.618442,-0.992920,-1.097192,-1.622894,...,-0.507993,1.276576,-0.160172,0.292175,-0.743238,-0.263644,0.795935,-0.238201,1.070725,-0.821936
4,0.141052,0.266566,-0.336276,-0.122118,-0.128361,-0.331527,0.770394,-0.992920,-1.097192,-1.622894,...,-0.245989,1.406788,0.688232,1.001529,-0.626161,-0.263644,0.795935,-0.496300,0.423968,-0.204827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3949,0.620502,-1.579584,-0.744338,0.138070,0.502808,0.080468,1.226250,-0.992920,-1.097192,-1.622894,...,0.381915,1.927638,-0.160172,0.459082,-0.567623,-0.731676,1.035906,-0.109151,3.010994,0.623861
3950,-1.057574,0.492625,0.145979,-0.100435,0.065845,-0.239973,1.065360,-0.992920,-1.097192,-1.622894,...,0.052152,1.276576,0.575111,0.834622,-0.509084,-0.965692,0.076019,-0.109151,0.294617,-0.028511
3951,-1.297299,0.492625,0.591138,-0.176323,0.308602,-0.056864,1.118990,-0.992920,-1.097192,-1.622894,...,0.490331,1.406788,0.914473,1.126709,-0.392008,-0.965692,1.275878,0.148948,0.812022,0.165438
3952,-1.297299,-0.486964,-0.336276,-0.393147,0.211499,-0.194195,1.306696,-0.992920,-1.097192,-1.622894,...,0.770403,1.016151,0.405430,0.625989,-0.567623,-1.199708,1.035906,-0.109151,0.682671,0.094911
3953,-1.297299,-0.750700,0.145979,0.105547,0.405705,0.126245,0.931284,-0.992920,-1.097192,-1.622894,...,0.178637,1.927638,1.536636,1.794337,-0.157855,-0.497660,1.275878,0.407047,1.070725,0.253596

### Train-test split for our label data(All nba players from the past vs 2020 players)

In [56]:
allnba_train=allnba.loc[allnba.Year<2020]

In [49]:
allnba_test=allnba.loc[allnba.Year==2020]

## 3 Model Building and prediction

### 3.1 KNN

In [58]:
from sklearn import neighbors

In [63]:
knn_predict = neighbors.KNeighborsClassifier(n_neighbors=1).fit(nbatrain_norm, allnba_train.ALLNBA).predict(nbatest_norm)

In [64]:
sum(knn_predict)

10

### KNN Algorithm with neighbor=1 gives us 10 players for 2020 ALL NBA teams

In [65]:
allnba_test.iloc[knn_predict == 1]

                     Player  Year  ALLNBA
3965  Giannis Antetokounmpo  2020       0
4039           Jimmy Butler  2020       0
4113            Joel Embiid  2020       0
4149            Rudy Gobert  2020       0
4171           James Harden  2020       0
4214           Kyrie Irving  2020       0
4223           LeBron James  2020       0
4270          Kawhi Leonard  2020       0
4273         Damian Lillard  2020       0
4480      Russell Westbrook  2020       0

### 3.2 SVM

In [66]:
from sklearn import svm

In [67]:
svm_predict = svm.SVC().fit(nbatrain_norm, allnba_train.ALLNBA).predict(nbatest_norm)

/Users/jerrytong/anaconda3/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

In [68]:
sum(svm_predict)

8

### SVM gives us 8 players for 2020 ALL NBA teams

In [69]:
allnba_test.iloc[svm_predict == 1]

                     Player  Year  ALLNBA
3965  Giannis Antetokounmpo  2020       0
4089          Anthony Davis  2020       0
4101            Luka Dončić  2020       0
4171           James Harden  2020       0
4223           LeBron James  2020       0
4270          Kawhi Leonard  2020       0
4273         Damian Lillard  2020       0
4499             Trae Young  2020       0

### 3.3 Naive Bayes

In [70]:
from sklearn import naive_bayes

In [71]:
nb_predict = naive_bayes.GaussianNB().fit(nbatrain_norm, allnba_train.ALLNBA).predict(nbatest_norm)

In [72]:
sum(nb_predict)

59

### Naive Bayes gives us 59 players for 2020 All NBA teams

In [74]:
allnba_test.iloc[nb_predict == 1]

                       Player  Year  ALLNBA
3955              Bam Adebayo  2020       0
3956        LaMarcus Aldridge  2020       0
3965    Giannis Antetokounmpo  2020       0
3992             Bradley Beal  2020       0
4007         Bojan Bogdanović  2020       0
4012             Devin Booker  2020       0
4029             Jaylen Brown  2020       0
4039             Jimmy Butler  2020       0
4044             Clint Capela  2020       0
4089            Anthony Davis  2020       0
4095            DeMar DeRozan  2020       0
4099        Spencer Dinwiddie  2020       0
4101              Luka Dončić  2020       0
4107           Andre Drummond  2020       0
4113              Joel Embiid  2020       0
4129            Evan Fournier  2020       0
4130             De'Aaron Fox  2020       0
4145              Paul George  2020       0
4148  Shai Gilgeous-Alexander  2020       0
4149              Rudy Gobert  2020       0
4153          Devonte' Graham  2020       0
4171             James Harden  2020       0
4177            Tobias Harris  2020       0
4192              Buddy Hield  2020       0
4197             Jrue Holiday  2020       0
4213           Brandon Ingram  2020       0
4223             LeBron James  2020       0
4235             Nikola Jokić  2020       0
4261              Zach LaVine  2020       0
4270            Kawhi Leonard  2020       0
4273           Damian Lillard  2020       0
4278               Kevin Love  2020       0
4279               Kyle Lowry  2020       0
4298              CJ McCollum  2020       0
4312          Khris Middleton  2020       0
4319         Donovan Mitchell  2020       0
4325                Ja Morant  2020       0
4327            Marcus Morris  2020       0
4361              Kelly Oubre  2020       0
4368               Chris Paul  2020       0
4383       Kristaps Porziņģis  2020       0
4386            Julius Randle  2020       0
4403             Terry Rozier  2020       0
4405         D'Angelo Russell  2020       0
4406         Domantas Sabonis  2020       0
4415            Collin Sexton  2020       0
4418            Pascal Siakam  2020       0
4420              Ben Simmons  2020       0
4434             Jayson Tatum  2020       0
4444         Tristan Thompson  2020       0
4449       Karl-Anthony Towns  2020       0
4459            Fred VanVleet  2020       0
4463           Nikola Vučević  2020       0
4467             Kemba Walker  2020       0
4473              T.J. Warren  2020       0
4480        Russell Westbrook  2020       0
4483         Hassan Whiteside  2020       0
4484           Andrew Wiggins  2020       0
4499               Trae Young  2020       0

### Harden, Lebron, Giannis, Dame and Kawhi appear in all model's prediction.

### Preliminary Analysis: I did not include team wins into player stats but that usually plays a factor toward All NBA selection. In the near future, I'll definitely include team wins into my models.